pipeline {
    agent any

    tools {
	maven 'maven_3.5.2'
	jdk 'jdk8'
	}

    stages {
        stage('Build') {
            steps {
		withMaven(maven : 'maven_3_5_0' ){
                sh 'mvn -B -DskipTests clean package'
		}
          }        
            }
        }
    
}
